version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=mlflow"
      - "POSTGRES_PASSWORD=mlflow_pass"
    ports:
      - "5532:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
     - "9900:9000"
     - "9100:9001"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    volumes: 
      - minio_data:/data
    command: minio server /data --console-address ":9001" 

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    environment:
      - "BACKEND_URI=postgresql://mlflow:mlflow_pass@postgres:5432"
      - "MLFLOW_S3_ENDPOINT_URL=http://minio:9000"
      - "ARTIFACT_ROOT=s3://mlflow-artifacts/"
      - "AWS_ACCESS_KEY_ID=mlflow_access_key"
      - "AWS_SECRET_ACCESS_KEY=mlflow_secret_key"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
