version: "3"

services:
  postgres:
    build:
        # seperate docker file for postgres
        dockerfile: Dockerfile_postgres
    #image: cycling_postgres --> to change later but need to update path
    env_file:
      - .env
    ports:
      - "5532:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
     - "9900:9000"
     - "9100:9001"
    env_file:
      - .env
    volumes: 
      - minio_data:/data
    command: minio server /data --console-address ":9000" --address ':9001'

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    image: cycling_mlflow
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
