version: "3"

services:
  postgres:
    build:
        # seperate docker file for postgres
        dockerfile: Dockerfile_postgres
    #image: cycling_postgres --> to change later but need to update path
    env_file:
      - .env
    ports:
      - "5532:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
     - "9900:9000"
     - "9100:9001"
    env_file:
      - .env
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    volumes: 
      - minio_data:/data
    command: minio server /data --console-address ":9000" --address ':9001'

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    image: cycling_mlflow
    ports:
      - "5050:5000"
    env_file:
      - .env
    environment:
      #MLFLOW_TRACKING_URI: "s3://test"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      MLFLOW_S3_ENDPOINT_URL: "http://minio:9001"
      #MINIO_ROOT_USER: 'minioadmin'
      #MINIO_ROOT_PASSWORD: 'minioadmin'
    depends_on:
      - postgres
      - minio
    #command: /bin/sh -c "export AWS_ACCESS_KEY_ID='minioadmin'; export AWS_SECRET_ACCESS_KEY='minioadmin'"

volumes:
  postgres_data:
  minio_data:
